name: CI Deploy
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^16
    runs-on: macos-latest
    steps:
      - uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: true # default = `false`
          configuration: release # no default, ie. `xcodebuild` decides itself
